### ISSUE TITLE
Classe Data

### ISSUE THREAD

**Issue by kyriosdata** [alicefng/cs-2019-01#13]
Não há um bom motivo para a classe Data armazenar uma data empregando 12 bytes. Algo similar a #12. Classe deve representar um conceito relevante de um domínio, se for data, então veja que há opções, além de [LocalDate](https://docs.oracle.com/javase/8/docs/api/java/time/LocalDate.html). Ou seja, o que foi requisitado é mais simples e não se beneficia pela existência dessa classe.

**Comment by alicefng** [comment]
Professor, eu tirei os atributos da classe e fiz outras modificações sugeridas pelo checkstyle, no final ficou como uma classe utilitária que não pode ser instanciada. Se mesmo assim achar melhor, eu posso colocar todas os métodos (das classes Matemática, Data e CPF) em um só arquivo como muitos alunos fizeram.

**Comment by kyriosdata** [comment]
Essa e uma classe utilitaria como Math, por exemplo.



Em qua, 15 de mai de 2019 20:55, Alice Francener <notifications@github.com>
escreveu:
