### ISSUE TITLE
Substituindo versão do Jackson empregada pelo Spring boot

### ISSUE THREAD

**Issue by kyriosdata** [alicefng/cs-2019-01#24]
Veja orientação em https://springframework.guru/jackson-dependency-issue-spring-boot-maven/
Desta forma fica esclarecido como fazer. 

Antes de fazer, contudo, seguiria outro caminho, pois este exige conhecimento e experiência acerca desta dependência do Spring Boot para o Jackson. Melhor seria se o Spring Boot resolvesse. A simples substituição pode introduzir outros problemas.

**Comment by alicefng** [comment]
Professor, sobre essa versão do Jackson, tentei substituir e não consegui, continuou dando erro, mesmo com as mudanças.

**Comment by kyriosdata** [comment]
Depois investigamos. Voce deve ter eliminado a dependwncia i troduzida pelo
SpringBoot, mas talvez outra dependencia esta sendo i troduzida. Como vc
mesmoja sabe mvn dependency:tree e a ferramenta para verificar isso

Fabio

Em seg, 1 de jul de 2019 18:27, Alice Francener <notifications@github.com>
escreveu:
