### ISSUE TITLE
Constantes como constantes

### ISSUE THREAD

**Issue by kyriosdata** [alicefng/cs-2019-01#7]
Em vez de 
```java
        int quociente = numero / 100;
        int resto = restoDaDivisaoInteira(numero, 100);
        int resultado = potencia(quociente + resto, 2);
```

melhor seria
```java
        final int quociente = numero / 100;
        final int resto = restoDaDivisaoInteira(numero, 100);
        final int resultado = potencia(quociente + resto, 2);
```

Em JavaScript teremos **const** em vez de **final**. Observe que este ajuste exige revisão de todo o código produzido.

**Comment by alicefng** [comment]
Corrigi isso em Java, o resultado do checkstyle ajudou. Em seguida, voltarei para os códigos em JavaScript para mudá-los.
